#ifndef OMNICPP_ENGINE_VERSION_H
#define OMNICPP_ENGINE_VERSION_H

#define OMNICPP_ENGINE_VERSION_MAJOR 1
#define OMNICPP_ENGINE_VERSION_MINOR 0
#define OMNICPP_ENGINE_VERSION_PATCH 0

#define OMNICPP_ENGINE_VERSION_STRING "1.0.0"

#endif // OMNICPP_ENGINE_VERSION_H
